name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      APP_BUILD_VERSION: ${{ format('3.1.{0}', github.run_number) }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      
      - name: Package (release)
        run: dotnet pack -c Release -p:PackageVersion=${{ env.APP_BUILD_VERSION }}

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1.5.5
      
      - name: Unit test
        run: dotnet test -p:PackageVersion=${{ env.APP_BUILD_VERSION }} test/NUnit.Xml.TestLogger.UnitTests/NUnit.Xml.TestLogger.UnitTests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      
      - name: Acceptance test
        if: ${{ matrix.os == 'windows-latest' }}
        run: dotnet test -p:PackageVersion=${{ env.APP_BUILD_VERSION }} test/NUnit.Xml.TestLogger.AcceptanceTests/NUnit.Xml.TestLogger.AcceptanceTests.csproj
     
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: test/NUnit.Xml.TestLogger.UnitTests/coverage.opencover.xml
      
      - name: Publish packages
        if: ${{ github.event_name == 'push' && matrix.os == 'windows-latest' }}
        run: |
          $packageFile = (Get-ChildItem src/package/bin/Release/*.nupkg).FullName
          dotnet nuget push "$packageFile" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/spekt/index.json
          dotnet nuget push "$packageFile" --api-key ${{ secrets.SPEKT_MYGET_KEY }} --source https://www.myget.org/F/spekt/api/v3/index.json
